
# This file was generated by the Tkinter Designer by Parth Jadhav
# https://github.com/ParthJadhav/Tkinter-Designer


from pathlib import Path
from os.path import dirname
# Explicit imports to satisfy Flake8
from tkinter import Tk, Canvas, Entry, Text, Button, PhotoImage, Radiobutton
from tkinter import *
from tkinter import ttk
from formdb import Database

db = Database("mydatabase.db")


OUTPUT_PATH = dirname(__file__)
ASSETS_PATH = OUTPUT_PATH + r"\assets\frame0"


def relative_to_assets(path: str) -> Path:
    return ASSETS_PATH / Path(path)


print(OUTPUT_PATH)
window = Tk()
window.title("Store Receipt Database")
window.geometry("1055x731")
window.configure(bg="#074A5E")


canvas = Canvas(
    window,
    bg="#074A5E",
    height=731,
    width=1055,
    bd=0,
    highlightthickness=0,
    relief="ridge"
)

canvas.place(x=0, y=0)
canvas.create_rectangle(
    35.0,
    35.0,
    631.0,
    357.0,
    fill="#FFFFFF",
    outline="")


itemClicked = StringVar(value="0")

# program functions

priceList = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12,
             13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25]
itemList = ["vinegar", "sugar", "soy", "salt", "oil", "egg", "potato", "tomato", "onion", "garlic", "sardines", "biscuit",
            "coffee", "milo", "milk", "ariel", "downy", "bars", "joy", "toothpaste", "mask", "alcohol", "shampoo", "conditioner", "rice"]


def dispalyAll():
    tv2.delete(*tv2.get_children())
    for row in db.fetch():
        tv2.insert("", END, values=row)
        # print(row)


def submitSelection():
    test = itemClicked.get()
    if test in itemList:
        i = itemList.index(test)
        # print(i)
    price = priceList[i]
    # print(price)


RButton_vinegar = Radiobutton(
    window, text="Vinegar",  variable=itemClicked, value="vinegar", background="#FFFFFF")
RButton_vinegar.place(
    x=60.0,
    y=100.0,
    width=100.0,
    height=30.0)

RButton_sugar = Radiobutton(
    window, text="Sugar",  variable=itemClicked, value="sugar", background="#FFFFFF")
RButton_sugar.place(
    x=57.0,
    y=135.0,
    width=100.0,
    height=30.0)

RButton_soy = Radiobutton(window, text="Soy Sauce",
                          variable=itemClicked, value="soy", background="#FFFFFF")
RButton_soy.place(
    x=57.0,
    y=170.0,
    width=100.0,
    height=30.0)

RButton_salt = Radiobutton(
    window, text="Salt",  variable=itemClicked, value="salt", background="#FFFFFF")
RButton_salt.place(
    x=57.0,
    y=205.0,
    width=100.0,
    height=30.0)

RButton_oil = Radiobutton(
    window, text="Oil",  variable=itemClicked, value="oil", background="#FFFFFF")
RButton_oil.place(
    x=57.0,
    y=240.0,
    width=100.0,
    height=30.0)

RButton_egg = Radiobutton(
    window, text="Egg",  variable=itemClicked, value="egg", background="#FFFFFF")
RButton_egg.place(
    x=165.0,
    y=100.0,
    width=100.0,
    height=30.0)

RButton_potato = Radiobutton(
    window, text="Potato",  variable=itemClicked, value="potato", background="#FFFFFF")
RButton_potato.place(
    x=165.0,
    y=135.0,
    width=100.0,
    height=30.0)

RButton_tomato = Radiobutton(
    window, text="Tomato",  variable=itemClicked, value="tomato", background="#FFFFFF")
RButton_tomato.place(
    x=165.0,
    y=170.0,
    width=100.0,
    height=30.0)

RButton_onion = Radiobutton(
    window, text="Onion",  variable=itemClicked, value="onion", background="#FFFFFF")
RButton_onion.place(
    x=165.0,
    y=205.0,
    width=100.0,
    height=30.0)

RButton_garlic = Radiobutton(
    window, text="Garlic",  variable=itemClicked, value="garlic", background="#FFFFFF")
RButton_garlic.place(
    x=165.0,
    y=240.0,
    width=100.0,
    height=30.0)

RButton_sardines = Radiobutton(
    window, text="Sardines",  variable=itemClicked, value="sardines", background="#FFFFFF")
RButton_sardines.place(
    x=270.0,
    y=100.0,
    width=100.0,
    height=30.0)

RButton_biscuit = Radiobutton(
    window, text="Biscuit",  variable=itemClicked, value="biscuit", background="#FFFFFF")
RButton_biscuit.place(
    x=270.0,
    y=135.0,
    width=100.0,
    height=30.0)

RButton_coffee = Radiobutton(window, text="Instant Coffee",
                             variable=itemClicked, value="coffee", background="#FFFFFF")
RButton_coffee.place(
    x=270.0,
    y=170.0,
    width=100.0,
    height=30.0)

RButton_milo = Radiobutton(
    window, text="Milo",  variable=itemClicked, value="milo", background="#FFFFFF")
RButton_milo.place(
    x=270.0,
    y=205.0,
    width=100.0,
    height=30.0)

RButton_milk = Radiobutton(
    window, text="Milk",  variable=itemClicked, value="milk", background="#FFFFFF")
RButton_milk.place(
    x=270.0,
    y=240.0,
    width=100.0,
    height=30.0)

RButton_ariel = Radiobutton(
    window, text="Ariel",  variable=itemClicked, value="ariel", background="#FFFFFF")
RButton_ariel.place(
    x=375.0,
    y=100.0,
    width=100.0,
    height=30.0)

RButton_downy = Radiobutton(
    window, text="Downy",  variable=itemClicked, value="downy", background="#FFFFFF")
RButton_downy.place(
    x=375.0,
    y=135.0,
    width=100.0,
    height=30.0)

RButton_bars = Radiobutton(window, text="Bar Soap",
                           variable=itemClicked, value="bars", background="#FFFFFF")
RButton_bars.place(
    x=375.0,
    y=170.0,
    width=100.0,
    height=30.0)

RButton_joy = Radiobutton(
    window, text="Joy",  variable=itemClicked, value="joy", background="#FFFFFF")
RButton_joy.place(
    x=375.0,
    y=205.0,
    width=100.0,
    height=30.0)

RButton_toothpaste = Radiobutton(
    window, text="Toothpaste",  variable=itemClicked, value="toothpaste", background="#FFFFFF")
RButton_toothpaste.place(
    x=375.0,
    y=240.0,
    width=100.0,
    height=30.0)

RButton_mask = Radiobutton(
    window, text="Mask",  variable=itemClicked, value="mask", background="#FFFFFF")
RButton_mask.place(
    x=480.0,
    y=100.0,
    width=100.0,
    height=30.0)

RButton_alcohol = Radiobutton(
    window, text="Alcohol",  variable=itemClicked, value="alcohol", background="#FFFFFF")
RButton_alcohol.place(
    x=480.0,
    y=135.0,
    width=100.0,
    height=30.0)

RButton_shampoo = Radiobutton(
    window, text="Shampoo",  variable=itemClicked, value="shampoo", background="#FFFFFF")
RButton_shampoo.place(
    x=480.0,
    y=170.0,
    width=100.0,
    height=30.0)

RButton_conditioner = Radiobutton(
    window, text="Conditioner",  variable=itemClicked, value="conditioner", background="#FFFFFF")
RButton_conditioner.place(
    x=480.0,
    y=205.0,
    width=100.0,
    height=30.0)

RButton_rice = Radiobutton(window, text="Rice Grain",
                           variable=itemClicked, value="rice", background="#FFFFFF")
RButton_rice.place(
    x=480.0,
    y=240.0,
    width=100.0,
    height=30.0)

button_image_1 = PhotoImage(
    file=relative_to_assets("button_1.png"))
button_1 = Button(
    image=button_image_1,
    borderwidth=0,
    highlightthickness=0,
    command=submitSelection,
    relief="flat"
)
button_1.place(
    x=349.0,
    y=292.0,
    width=216.0,
    height=39.0
)

button_image_2 = PhotoImage(
    file=relative_to_assets("button_2.png"))
button_2 = Button(
    image=button_image_2,
    borderwidth=0,
    highlightthickness=0,
    command=lambda: print("button_2 clicked"),
    relief="flat"
)
button_2.place(
    x=698.0,
    y=584.0,
    width=270.0,
    height=39.0
)

button_image_3 = PhotoImage(
    file=relative_to_assets("button_3.png"))
button_3 = Button(
    image=button_image_3,
    borderwidth=0,
    highlightthickness=0,
    command=lambda: print("button_3 clicked"),
    relief="flat"
)
button_3.place(
    x=698.0,
    y=638.0,
    width=270.0,
    height=39.0
)

entry_image_1 = PhotoImage(
    file=relative_to_assets("entry_1.png"))
entry_bg_1 = canvas.create_image(
    268.0,
    311.5,
    image=entry_image_1
)
entry_1 = Entry(
    bd=0,
    bg="#D9D9D9",
    fg="#000716",
    highlightthickness=0
)
entry_1.place(
    x=222.0,
    y=297.0,
    width=92.0,
    height=27.0
)

canvas.create_rectangle(
    50.0,
    91.996826171875,
    585.0009765625,
    95.0,
    fill="#000000",
    outline="")

canvas.create_rectangle(
    50.0,
    279.0,
    585.0009765625,
    282.003173828125,
    fill="#000000",
    outline="")

canvas.create_text(
    51.0,
    56.0,
    anchor="nw",
    text="ITEMS",
    fill="#000000",
    font=("TimesNewRomanPSMT", 25 * -1)
)

canvas.create_text(
    71.0,
    301.0,
    anchor="nw",
    text="QUANTITY",
    fill="#000000",
    font=("TimesNewRomanPSMT", 18 * -1)
)

canvas.create_rectangle(
    35.0,
    374.0,
    631.0,
    696.0,
    fill="#FFFFFF",
    outline="")

canvas.create_rectangle(
    35.0,
    441.0,
    184.0,
    486.0,
    fill="#B8BEC0",
    outline="")

canvas.create_rectangle(
    184.0,
    441.0,
    333.0,
    486.0,
    fill="#B8BEC0",
    outline="")

canvas.create_rectangle(
    333.0,
    441.0,
    482.0,
    486.0,
    fill="#B8BEC0",
    outline="")

canvas.create_rectangle(
    482.0,
    441.0,
    631.0,
    486.0,
    fill="#B8BEC0",
    outline="")

canvas.create_text(
    52.0,
    452.0,
    anchor="nw",
    text="Transaction ID",
    fill="#000000",
    font=("TimesNewRomanPSMT", 18 * -1)
)

canvas.create_text(
    224.0,
    452.0,
    anchor="nw",
    text="Total Fee",
    fill="#000000",
    font=("TimesNewRomanPSMT", 18 * -1)
)

canvas.create_text(
    375.0,
    452.0,
    anchor="nw",
    text="Payment",
    fill="#000000",
    font=("TimesNewRomanPSMT", 18 * -1)
)

canvas.create_text(
    524.0,
    452.0,
    anchor="nw",
    text="Change",
    fill="#000000",
    font=("TimesNewRomanPSMT", 18 * -1)
)

canvas.create_rectangle(
    35.0,
    374.0,
    631.0,
    439.0,
    fill="#8DC1CF",
    outline="")

canvas.create_text(
    264.0,
    391.0,
    anchor="nw",
    text="DATABASE",
    fill="#000000",
    font=("TimesNewRomanPSMT", 27 * -1)
)

canvas.create_rectangle(
    33.0,
    439.0,
    631.0,
    441.0,
    fill="#000000",
    outline="")

canvas.create_rectangle(
    33.0,
    484.0,
    631.0,
    486.0,
    fill="#000000",
    outline="")

canvas.create_rectangle(
    181.0,
    439.0,
    183.0,
    486.0,
    fill="#000000",
    outline="")

canvas.create_rectangle(
    331.0,
    439.0,
    333.0,
    486.0,
    fill="#000000",
    outline="")

canvas.create_rectangle(
    479.0,
    439.0,
    481.0,
    486.0,
    fill="#000000",
    outline="")

canvas.create_rectangle(
    648.0,
    35.0,
    1020.0,
    560.0,
    fill="#FFFFFF",
    outline="")

entry_image_2 = PhotoImage(
    file=relative_to_assets("entry_4.png"))
entry_bg_2 = canvas.create_image(
    905.5,
    446.5,
    image=entry_image_2
)
entry_2 = Entry(
    bd=0,
    bg="#D9D9D9",
    fg="#000716",
    highlightthickness=0
)
entry_2.place(
    x=822.0,
    y=434.0,
    width=168.0,
    height=27.0
)

# entry_image_3 = PhotoImage(
#     file=relative_to_assets("entry_3.png"))
# entry_bg_3 = canvas.create_image(
#     945.0,
#     446.5,
#     image=entry_image_3
# )
# entry_3 = Entry(
#     bd=0,
#     bg="#D9D9D9",
#     fg="#000716",
#     highlightthickness=0
# )
# entry_3.place(
#     x=899.0,
#     y=432.0,
#     width=92.0,
#     height=27.0
# )

entry_image_4 = PhotoImage(
    file=relative_to_assets("entry_4.png"))
entry_bg_4 = canvas.create_image(
    907.0,
    486.5,
    image=entry_image_4
)
entry_4 = Entry(
    bd=0,
    bg="#D9D9D9",
    fg="#000716",
    highlightthickness=0
)
entry_4.place(
    x=823.0,
    y=472.0,
    width=168.0,
    height=27.0
)

entry_image_5 = PhotoImage(
    file=relative_to_assets("entry_5.png"))
entry_bg_5 = canvas.create_image(
    907.0,
    526.5,
    image=entry_image_5
)
entry_5 = Entry(
    bd=0,
    bg="#D9D9D9",
    fg="#000716",
    highlightthickness=0
)
entry_5.place(
    x=823.0,
    y=512.0,
    width=168.0,
    height=27.0
)

canvas.create_rectangle(
    677.0,
    169.0,
    816.0,
    199.0,
    fill="#B8BEC0",
    outline="")

canvas.create_rectangle(
    823.0,
    169.0,
    892.0,
    199.0,
    fill="#B8BEC0",
    outline="")

canvas.create_rectangle(
    899.0,
    169.0,
    991.0,
    199.0,
    fill="#B8BEC0",
    outline="")

canvas.create_text(
    719.0,
    174.0,
    anchor="nw",
    text="ITEMS",
    fill="#000000",
    font=("TimesNewRomanPSMT", 18 * -1)
)

canvas.create_text(
    839.0,
    174.0,
    anchor="nw",
    text="QTY",
    fill="#000000",
    font=("TimesNewRomanPSMT", 18 * -1)
)

canvas.create_text(
    916.0,
    174.0,
    anchor="nw",
    text="TOTAL",
    fill="#000000",
    font=("TimesNewRomanPSMT", 18 * -1)
)

canvas.create_text(
    682.0,
    56.0,
    anchor="nw",
    text="SALES",
    fill="#000000",
    font=("TimesNewRomanPSMT", 25 * -1)
)

canvas.create_rectangle(
    674.0,
    92.0,
    991.0,
    95.996826171875,
    fill="#000000",
    outline="")

canvas.create_rectangle(
    674.0,
    415.0,
    991.0,
    418.996826171875,
    fill="#000000",
    outline="")

button_image_4 = PhotoImage(
    file=relative_to_assets("button_4.png"))
button_4 = Button(
    image=button_image_4,
    borderwidth=0,
    highlightthickness=0,
    command=lambda: print("button_4 clicked"),
    relief="flat"
)
button_4.place(
    x=875.0,
    y=110.0,
    width=116.0,
    height=39.0
)

button_image_5 = PhotoImage(
    file=relative_to_assets("button_5.png"))
button_5 = Button(
    image=button_image_5,
    borderwidth=0,
    highlightthickness=0,
    command=lambda: print("button_5 clicked"),
    relief="flat"
)
button_5.place(
    x=677.0,
    y=110.0,
    width=183.0,
    height=39.0
)

canvas.create_text(
    698.0,
    436.0,
    anchor="nw",
    text="TOTAL",
    fill="#000000",
    font=("TimesNewRomanPSMT", 18 * -1)
)

canvas.create_text(
    698.0,
    476.0,
    anchor="nw",
    text="PAYMENT",
    fill="#000000",
    font=("TimesNewRomanPSMT", 18 * -1)
)

canvas.create_text(
    698.0,
    517.0,
    anchor="nw",
    text="CHANGE",
    fill="#000000",
    font=("TimesNewRomanPSMT", 18 * -1)
)

tv = ttk.Treeview(columns=(1, 2, 3), style="mystyle.Treeview")
tv.place(
    x=675.0,
    y=165.0,
    width=320,
    height=225)
tv.heading("1", text="ITEM")
tv.column("1", width=50)
tv.heading("2", text="QTY")
tv.column("2", width=50)
tv.heading("3", text="SUBTOTAL")
tv.column("3", width=50)
tv['show'] = 'headings'


tv2 = ttk.Treeview(columns=(1, 2, 3, 4), style="mystyle.Treeview")
tv2.place(
    x=35.0,
    y=440.0,
    width=596,
    height=256)
tv2.heading("1", text="Transaction ID")
tv2.column("1", width=50)
tv2.heading("2", text="Total Fee")
tv2.column("2", width=50)
tv2.heading("3", text="Payment")
tv2.column("3", width=50)
tv2.heading("4", text="Change")
tv2.column("4", width=50)
tv2['show'] = 'headings'


window.resizable(False, False)


dispalyAll()
window.mainloop()
